name: Run clojure tests
on: [push]
jobs:
  clojure:
    runs-on: ubuntu-latest

    # env:
      # DATABASE_URL: "postgresql://postgres/clojure_jobs_luminus_test?user=postgres&password=postgres"
      # DATABASE_URL: postgres://postgres@postgres:5432/clojure

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Add config file
        run: echo '{:database-url "postgresql://localhost/clojure_jobs_luminus_test?user=postgres&password=postgres"}' > test-config.edn
        shell: bash

      - name: Create test database
        run: createdb clojure_jobs_luminus_test
        env:
          PGUSER: postgres
          PGPASSWORD: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          cli: 1.10.3 # Clojure CLI based on tools.deps
          lein: 'latest'     # or use 'latest' to always provision latest version of leiningen

      - name: Run tests
        run: lein test
        shell: bash
