name: Run clojure tests
on: [push]
jobs:
  clojure:
    runs-on: ubuntu-latest

    # env:
      # DATABASE_URL: "postgresql://postgres/clojure_jobs_luminus_test?user=postgres&password=postgres"
      # DATABASE_URL: postgres://postgres@postgres:5432/clojure

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --name pg_db
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Add config file
        run: cp ci-config.edn test-config.edn

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.3    # Clojure CLI based on tools.deps
          lein: 'latest'

      - name: Create test database
        run: lein run -m clojure-jobs-luminus.tasks.db-setup

      - name: Run tests
        run: lein test
        shell: bash
