name: Run clojure tests
on: [push]
jobs:
  clojure:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "postgresql://localhost/clojure_jobs_luminus_test?user=postgres&password="

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: clojure
          POSTGRES_PASSWORD: ''
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          cli: 1.10.3 # Clojure CLI based on tools.deps
          lein: 'latest'     # or use 'latest' to always provision latest version of leiningen
          #boot: 2.8.3     # or use 'latest' to always provision latest version of boot

      - name: Run tests
        run: lein test
        shell: bash
